const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/health', (req, res) => res.json({ status: 'Server is running!' }));
app.use('/api/users', (req, res) => res.json({ success: true }));
app.use('/api/jobs', (req, res) => res.json({ success: true }));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server on ${PORT}`));
